"""NHC forecast track and uncertainty cone for an active storm.

``CurrentStorms.json`` gives a storm's *current* position only. During an
actual event the current dot is not what anyone looks at -- the forecast track
and the cone of uncertainty are. NHC publishes both as KMZ (a zip holding one
KML) at a predictable per-storm URL::

    https://www.nhc.noaa.gov/storm_graphics/api/{STORMID}_TRACK_latest.kmz
    https://www.nhc.noaa.gov/storm_graphics/api/{STORMID}_CONE_latest.kmz

where ``STORMID`` is the uppercase basin id, e.g. ``AL092024`` for Helene.

Parsing uses only the standard library: ``zipfile`` for the container and a
narrow regex over the KML. A full XML parse would be more principled, but the
documents are machine-generated by NHC in a fixed shape and the regex fails
closed -- any surprise yields an empty result rather than a wrong track.
"""
from __future__ import annotations

import logging
import re
import zipfile
from io import BytesIO

import requests

log = logging.getLogger(__name__)

KMZ_URL = "https://www.nhc.noaa.gov/storm_graphics/api/{storm_id}_{product}_latest.kmz"

_COORDS_RE = re.compile(r"<coordinates>\s*([^<]+?)\s*</coordinates>", re.S)
_PLACEMARK_RE = re.compile(r"<Placemark>(.*?)</Placemark>", re.S)
_STYLE_RE = re.compile(r"<styleUrl>\s*#?([^<]+?)\s*</styleUrl>")
_LINESTRING_RE = re.compile(r"<LineString>.*?</LineString>", re.S)
_POLYGON_RE = re.compile(r"<Polygon>.*?</Polygon>", re.S)

# A cone polygon can carry hundreds of vertices; Leaflet does not need them all
# and every one is bytes in the page.
MAX_CONE_POINTS = 160
MAX_TRACK_POINTS = 40


def _parse_coordinates(blob: str) -> list[dict]:
    """KML ``lon,lat[,alt]`` triples -> ``[{"lat": .., "lon": ..}]``."""
    out: list[dict] = []
    for token in blob.split():
        parts = token.split(",")
        if len(parts) < 2:
            continue
        try:
            lon, lat = float(parts[0]), float(parts[1])
        except ValueError:
            continue
        if not (-90.0 <= lat <= 90.0 and -180.0 <= lon <= 180.0):
            continue
        out.append({"lat": lat, "lon": lon})
    return out


def _thin(points: list[dict], limit: int) -> list[dict]:
    """Evenly drop points beyond ``limit``, always keeping first and last."""
    if len(points) <= limit:
        return points
    step = len(points) / float(limit)
    kept = [points[int(i * step)] for i in range(limit)]
    if kept[-1] != points[-1]:
        kept[-1] = points[-1]
    return kept


def _fetch_kml(storm_id: str, product: str, timeout: int) -> str | None:
    url = KMZ_URL.format(storm_id=storm_id.upper(), product=product)
    try:
        r = requests.get(url, timeout=timeout,
                         headers={"User-Agent": "hurricane-asheville/0.1"})
        if r.status_code == 404:
            log.info("NHC %s product not published for %s", product, storm_id)
            return None
        r.raise_for_status()
        with zipfile.ZipFile(BytesIO(r.content)) as z:
            names = [n for n in z.namelist() if n.lower().endswith(".kml")]
            if not names:
                return None
            return z.read(names[0]).decode("utf-8", "replace")
    except Exception as exc:  # noqa: BLE001
        # Deliberately broad: this runs while a hurricane is approaching and a
        # missing graphic must never be the thing that takes the page down.
        log.info("NHC %s fetch failed for %s: %s", product, storm_id, exc)
        return None


def parse_track(kml: str) -> list[dict]:
    """Forecast track path from a TRACK KML.

    The document holds several line placemarks (72-hour and 120-hour). Take the
    longest, which is the full forecast path.
    """
    best: list[dict] = []
    for pm in _PLACEMARK_RE.findall(kml or ""):
        if not _LINESTRING_RE.search(pm):
            continue
        for blob in _COORDS_RE.findall(pm):
            pts = _parse_coordinates(blob)
            if len(pts) > len(best):
                best = pts
    return _thin(best, MAX_TRACK_POINTS)


def parse_cone(kml: str) -> list[dict]:
    """Cone-of-uncertainty polygon from a CONE KML."""
    best: list[dict] = []
    for pm in _PLACEMARK_RE.findall(kml or ""):
        if not _POLYGON_RE.search(pm):
            continue
        for blob in _COORDS_RE.findall(pm):
            pts = _parse_coordinates(blob)
            if len(pts) > len(best):
                best = pts
    if not best:
        # Some cone products wrap the polygon without a Placemark element.
        for blob in _COORDS_RE.findall(kml or ""):
            pts = _parse_coordinates(blob)
            if len(pts) > len(best):
                best = pts
    return _thin(best, MAX_CONE_POINTS)


def fetch_forecast(storm_id: str, timeout: int = 20) -> dict:
    """Track path and cone polygon for one storm.

    Returns ``{"forecast_track": [...], "cone": [...]}`` with empty lists when
    NHC has not published the product -- never raises, so one missing graphic
    cannot take the dashboard down mid-storm.
    """
    if not storm_id:
        return {"forecast_track": [], "cone": []}
    track_kml = _fetch_kml(storm_id, "TRACK", timeout)
    cone_kml = _fetch_kml(storm_id, "CONE", timeout)
    return {
        "forecast_track": parse_track(track_kml) if track_kml else [],
        "cone": parse_cone(cone_kml) if cone_kml else [],
    }


def attach_forecasts(storms: list, timeout: int = 20) -> list[dict]:
    """Enrich ``ActiveStorm`` dicts with their NHC track and cone.

    Runs in parallel: during a busy Atlantic period there may be several
    systems and each costs two requests.
    """
    from concurrent.futures import ThreadPoolExecutor
    if not storms:
        return []

    def _one(storm: dict) -> dict:
        try:
            return {**storm, **fetch_forecast(storm.get("id", ""), timeout)}
        except Exception as exc:  # noqa: BLE001
            log.warning("storm forecast enrich failed (%s): %s",
                        storm.get("name"), exc)
            return {**storm, "forecast_track": [], "cone": []}

    with ThreadPoolExecutor(max_workers=min(4, len(storms))) as pool:
        return list(pool.map(_one, storms))
